# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e806623f1b0498dd8c99ad5f644346a1f7c6433ccab23e3514ad672da747444fc4918ef2dc2f3725b2784caef3601a35979affd7b244e3f40c382dd4d19df9e8

test:
  secret_key_base: 4d5d52cc992c1bf3788378d4fa1d8b38b80692eb6e0c1245130432cbb465dce1254c04e81dc289dce55e6e1f71026901e5dd5b48f9a05b6c8cb111ca4550cd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
